### ISSUE TITLE
Check recommended classes

### ISSUE THREAD

**Issue by StanCallewaert** [oSoc15/dcat-validator.js#2]
Add warnings if the recommended classes aren't present.

**Comment by pietercolpaert** [comment]
Hey @StanCallewaert, it would be awesome that you would close issues through git commits. Check this out: https://help.github.com/articles/closing-issues-via-commit-messages/

If your commit message is `fix #2`, then it's going to close automatically, and the commit will be referenced in this issue. This makes it easy to see how certain issues were tackled :)
