### ISSUE TITLE
Add validation by file upload and URI

### ISSUE THREAD

**Issue by StanCallewaert** [oSoc15/dcat-validator.js#6]
Include these functionalities in this library. Only if the line numbers are already done.

**Comment by coreation** [comment]
@StanCallewaert this only needs to be in the front-end by @sebastienhenau , your library only needs to read Turtle, validate the dcat fields and return errors and warnings. @sebastienhenau will read the file and textarea, parse it and serialize it to Turtle. So this issue can be closed, or referenced from the dcat-validator front-end repository.
