### ISSUE TITLE
Change the code strategy to recursive methods

### ISSUE THREAD

**Issue by StanCallewaert** [oSoc15/dcat-validator.js#9]
## What happens now:

The code now loops over every DCAT class and in these classes it loops over the class his properties.
## The problem:

Some properties in a class are relationships. A relationship is a property that is a link between two classes. This implies that if there is a relationship in a class, that the class that the relationship points to will have to be checked to. That class can also have a relationship and so on.
## The solution:

With recursive methods we can check if a class has relationship. If it has a relationship, the class of the relationship can be checked, if that class has a relationship, that class can be checked, ...
## What needs to happen:

The current code has to be rebuild to recursive code and the JSON validator rules need to change. The validator rules will have a mandatory beginning like Catalog, Agent and Dataset (these classes need to be in a DCAT feed). The validator rules will also have another array with the non-mandatory classes in it.

**Comment by coreation** [comment]
Hi @StanCallewaert nice explanation of what needs to happen, so the cherry on the pie would be to use markdown to make up your description. Use #, ## and ### etc. to mark paragraphs.

**Comment by StanCallewaert** [comment]
This method created the new issue #10.
